const S=JSON.parse(localStorage.getItem("arquivo17-save")||"null")||{chapter:1,clues:[],choices:{},contactsUnlocked:["Noah"],sound:true,ending:null,first:false,group:false,clock:0};
const people={Noah:{age:19,initial:"N",number:"(21) 98841-2736",bio:"Amigo próximo de Lívia. Reservado. Parece saber mais do que diz."},Helena:{age:19,initial:"H",number:"(21) 99632-8417",bio:"Melhor amiga de Lívia. Emocional e evasiva."},Caio:{age:20,initial:"C",number:"(21) 98154-2098",bio:"Conhecia Lívia há anos. Brincalhão, mas muda quando o assunto é a noite do desaparecimento."},Miguel:{age:21,initial:"M",number:"(21) 99713-6402",bio:"Entende de tecnologia e recuperação de arquivos."},Sofia:{age:18,initial:"S",number:"(21) 98220-7315",bio:"Desconfiada de Noah. Guarda capturas que ninguém mais viu."},Daniel:{age:22,initial:"D",number:"(21) 97510-4418",bio:"Trabalha à noite e conhece o lugar ligado ao caso."}};
const clues={
1:["Pista #01 — 17","O número aparece no primeiro contato de Noah e no horário 23:17."],
2:["Pista #02 — O celular","Lívia deixou o aparelho para trás, mas o aparelho continua enviando dados."],
3:["Pista #03 — A fotografia","No fundo da foto existe uma porta marcada com o mesmo símbolo."],
4:["Pista #04 — 03:17","Um registro apagado aponta para 03:17 na noite do desaparecimento."],
5:["Pista #05 — 17","A sequência 17-03-21-17 abre uma nota escondida."],
6:["Pista #06 — A voz","A gravação de 17 segundos contém uma voz que pede para não confiar em Noah."],
7:["Pista #07 — O endereço","Uma coordenada leva a uma casa abandonada próxima ao antigo observatório."],
8:["Pista #08 — Arquivo corrompido","Miguel recupera um vídeo fragmentado: Lívia estava investigando o próprio grupo."],
9:["Pista #09 — O silêncio","As mentiras dos personagens se encaixam: cada um escondeu uma parte daquela noite."],
10:["Pista #10 — ARQUIVO 17","O arquivo não é uma pessoa. É um protocolo criado para registrar quem procura a verdade."]};
function save(){localStorage.setItem("arquivo17-save",JSON.stringify(S))}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("toast-on");setTimeout(()=>x.classList.remove("toast-on"),2400)}
function beep(type="click"){if(!S.sound)return; try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=type==="notify"?520:type==="call"?220:330;o.type="sine";g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch(e){}}
function nowTime(){let mins=23*60+17+S.clock;let h=Math.floor((mins/60)%24),m=mins%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}
function tick(){document.getElementById("clock").textContent=nowTime();const l=document.querySelector(".lock .time");if(l)l.textContent=nowTime()}
setInterval(()=>{S.clock++;tick();save()},1000);tick();

function render(v){document.getElementById("screen").innerHTML=v;document.getElementById("screen").scrollTop=0}
function home(){beep();render(`<div class="home"><div class="homehead"><div><div class="time">${nowTime()}</div><small>19 DE SETEMBRO • SÁBADO</small></div><div>▰ 87%</div></div><div class="widget"><b>NOTIFICAÇÃO</b><p>${S.first?"ARQUIVO 17 — novas atividades detectadas.":"Nenhuma atividade recente."}</p></div><div class="apps">
${app("💬","Mensagens","messages()")}${app("👥","Contatos","contacts()")}${app("📞","Telefone","phone()")}${app("🔎","Investigação","investigation()")}
${app("🖼️","Galeria","gallery()")}${app("📂","Arquivos","files()")}${app("📝","Notas","notes()")}${app("🌐","Navegador","browser()")}
${app("👥","Grupo","group()")}${app("⚙️","Ajustes","settings()")}
</div></div>`)}
function app(i,n,f){return `<button class="app" onclick="${f}"><div class="icon">${i}</div><span>${n}</span></button>`}
function lock(){render(`<div class="lock"><div class="case-title">ARQUIVO 17</div><div class="time">${nowTime()}</div><div class="date">19 DE SETEMBRO • SÁBADO</div><div class="notify"><b>NÚMERO DESCONHECIDO</b><p>Giovanna?</p></div><div class="swipe">toque para desbloquear</div><button class="primary" style="margin-top:22px" onclick="home()">DESBLOQUEAR</button></div>`)}
function start(){render(`<div class="start"><div class="tag">CASO // 17</div><h1 class="glitch">ARQUIVO<br>17</h1><p style="color:#a2adbd">UM CASO QUE NUNCA DEVERIA TER SIDO ABERTO.</p><div class="menu"><button class="primary" onclick="begin()">INICIAR INVESTIGAÇÃO</button><button class="secondary" onclick="S.first?home():toast('Nenhum progresso encontrado.')">CONTINUAR</button><button class="secondary" onclick="settings()">CONFIGURAÇÕES</button></div></div>`)}
function begin(){S.first=true;S.chapter=1;S.clock=0;save();beep("notify");chat("Noah",0)}
function top(t){return `<div class="top"><button onclick="home()">‹</button><h2>${t}</h2></div>`}
function messages(){render(`<div class="page">${top("Mensagens")}<div class="list">${S.contactsUnlocked.map(n=>`<button onclick="chat('${n}',0)"><div class="row"><div class="avatar">${people[n].initial}</div><div><b>${n}</b><div class="muted">${people[n].bio.slice(0,45)}…</div></div></div></button>`).join("")}<button onclick="chat('Desconhecido',0)"><div class="row"><div class="avatar">?</div><div><b>Número desconhecido</b><div class="muted">Última mensagem: você não deveria estar falando com Noah.</div></div></div></button></div></div>`)}
function chat(name,step=0){
if(name==="Desconhecido"){render(`<div class="page">${top("Número desconhecido")}<div class="chat"><div class="bubble"><div class="name">DESCONHECIDO • 23:21</div>Você não deveria estar falando com Noah.</div><div class="bubble"><div class="name">DESCONHECIDO</div>Mas agora que começou… não pare.</div></div></div>`);return}
let arr=[];
if(name==="Noah"){arr=[["Noah","Giovanna?"],["Noah","Se você recebeu isso, significa que eu não consegui voltar."],["Noah","Lívia Moraes desapareceu há alguns dias."],["Noah","Ela deixou o celular para trás. Só que o celular começou a enviar mensagens sozinho."],["Noah","Não conte a ninguém que está investigando."]]}
if(name==="Helena"){arr=[["Helena","Você é a Giovanna, né?"],["Helena","Noah falou com você?"],["Helena","Não quero que você se meta nisso."],["Helena","Lívia estava assustada antes de sumir."]]}
if(name==="Caio"){arr=[["Caio","Então você é a investigadora agora? kkk"],["Caio","Olha, eu não vi nada naquela noite."],["Caio","Só não pergunta sobre 03:17."]]}
if(name==="Miguel"){arr=[["Miguel","Noah me pediu para olhar um arquivo."],["Miguel","Tem alguma coisa apagada do celular da Lívia."],["Miguel","Preciso de uma senha: 17-03-21-17."]]}
if(name==="Sofia"){arr=[["Sofia","Eu não confio no Noah."],["Sofia","Se ele te disse que queria ajudar, cuidado."],["Sofia","Tenho uma captura que pode mudar tudo."]]}
const visible=Math.min(arr.length,step+1);
render(`<div class="page">${top(name)}<div class="row" style="margin-bottom:15px"><div class="avatar">${people[name].initial}</div><div><b>${name}</b><div class="muted">${people[name].age} anos • ${people[name].number}</div></div></div><div class="chat">${arr.slice(0,visible).map(x=>`<div class="bubble"><div class="name">${x[0].toUpperCase()}</div>${x[1]}</div>`).join("")}</div>
${visible<arr.length?`<div class="typing">digitando…</div><button class="primary" onclick="beep('notify');chat('${name}',${step+1});advance('${name}',${step})">Continuar</button>`:`<div class="choices">${choices(name)}</div>`}</div>`);
}
function choices(name){
if(name==="Noah")return `<button onclick="choice('trust',1);unlock('Helena');chapter(2)">[ O que aconteceu com Lívia? ]</button><button onclick="choice('trust',0);unlock('Sofia');chapter(2)">[ Como conseguiu meu número? ]</button>`;
if(name==="Helena")return `<button onclick="choice('helena',1);unlock('Miguel');chapter(3)">[ O que você está escondendo? ]</button><button onclick="choice('helena',0);chapter(3)">[ Vou descobrir sozinha. ]</button>`;
if(name==="Caio")return `<button onclick="choice('caio',1);chapter(4)">[ O que aconteceu às 03:17? ]</button><button onclick="choice('caio',0);chapter(4)">[ Tudo bem. ]</button>`;
if(name==="Miguel")return `<button onclick="unlock('Daniel');chapter(5)">[ Abrir o arquivo 17-03-21-17 ]</button>`;
if(name==="Sofia")return `<button onclick="chapter(4);clue(3)">[ Me envie a captura. ]</button>`;
return "";
}
function advance(n,s){if(n==="Noah"&&s===4){clue(2)}}
function choice(k,v){S.choices[k]=v;save();toast("Escolha registrada.");}
function unlock(n){if(!S.contactsUnlocked.includes(n))S.contactsUnlocked.push(n);save();toast(`${n} adicionado aos contatos`)}
function clue(n){if(!S.clues.includes(n)){S.clues.push(n);save();beep("notify");toast("🔎 NOVA PISTA: "+clues[n][0])}}
function chapter(n){S.chapter=Math.max(S.chapter,n);save();setTimeout(()=>chapterScreen(n),500)}
function chapterScreen(n){clue(Math.min(n,10));render(`<div class="page" style="display:flex;min-height:100%;align-items:center;justify-content:center"><div style="text-align:center"><div class="muted">CAPÍTULO ${n}</div><h2>${["","O número desconhecido","Lívia","O grupo","A fotografia","17","A ligação","O lugar","O arquivo apagado","A verdade","Arquivo 17"][n]}</h2><p class="muted">Pistas encontradas: ${S.clues.length}<br>Mensagens recebidas: ${n*3}<br>Confiança: ${trust()}</p><button class="primary" onclick="${n===10?'ending()':'home()'}">CONTINUAR</button></div></div>`)}
function trust(){return (S.choices.trust?2:1)+(S.choices.helena?1:0)}
function investigation(){render(`<div class="page">${top("INVESTIGAÇÃO")}<div class="card"><b>CASO LÍVIA MORAES</b><p class="muted">Desaparecimento • status: ativo</p></div>${S.clues.map(n=>`<div class="card clue"><b>${clues[n][0]}</b><p class="muted">${clues[n][1]}</p></div>`).join("")||'<div class="card muted">Nenhuma pista encontrada ainda.</div>'}<div class="card"><b>LINHA DO TEMPO</b><p class="mono">23:17 — primeira mensagem<br>23:41 — chamada perdida<br>00:13 — arquivo recebido<br>01:07 — número desconhecido<br>02:17 — acesso ao ARQUIVO 17</p></div></div>`)}
function contacts(){render(`<div class="page">${top("Contatos")}<div class="list">${S.contactsUnlocked.map(n=>`<button onclick="chat('${n}',0)"><div class="row"><div class="avatar">${people[n].initial}</div><div><b>${n}</b><div class="muted">${people[n].number}</div></div></div></button>`).join("")}</div></div>`)}
function phone(){render(`<div class="page">${top("Telefone")}<div class="card"><b>CHAMADAS RECENTES</b><p class="muted">23:41 • PRIVADO • perdida</p><p class="muted">23:17 • NOAH • recebida</p><p class="muted">02:17 • +55 21 0000-0017 • perdida</p></div><button class="primary" onclick="incoming()">📞 Simular chamada recebida</button></div>`)}
function incoming(){beep("call");render(`<div class="call"><div class="bigavatar">?</div><div class="caller">NÚMERO DESCONHECIDO</div><div class="number">PRIVADO</div><div class="call-actions"><button onclick="answer()">ATENDER</button><button class="danger" onclick="phone();toast('Chamada recusada')">RECUSAR</button></div></div>`)}
function answer(){let t=0;render(`<div class="call"><div class="bigavatar">?</div><div class="caller">NÚMERO DESCONHECIDO</div><div class="timer" id="ct">00:00</div><div class="card"><b>VOZ DESCONHECIDA</b><p id="voice">"Você está sozinha?"</p></div><div class="choices"><button onclick="callReply('sim')">[ Sim ]</button><button onclick="callReply('nao')">[ Não ]</button><button onclick="callReply('quem')">[ Quem é você? ]</button></div></div>`);const iv=setInterval(()=>{t++;let x=document.getElementById("ct");if(x)x.textContent=`00:${String(t).padStart(2,"0")}`;if(t>17){clearInterval(iv)}},1000)}
function callReply(x){clue(6);document.getElementById("voice").textContent=x==="quem"?"Eu sou a parte que você ainda não encontrou.":"Então você já começou a mentir.";toast("A chamada terminou.");setTimeout(()=>investigation(),1300)}
function gallery(){render(`<div class="page">${top("Galeria")}<div class="photo">IMG_0017<br>porta / símbolo / 03:17</div><div class="photo">IMG_0009<br>grupo de amigos — arquivo corrompido</div><div class="photo">IMG_0031<br>corredor escuro — sem localização</div><button class="primary" onclick="clue(3);toast('Metadados recuperados: 03:17')">ANALISAR FOTOS</button></div>`)}
function files(){render(`<div class="page">${top("Arquivos")}<div class="list"><button onclick="file17()">📄 IMG_0017 <span class="badge">1.8 MB</span></button><button onclick="clue(8);toast('Arquivo corrompido parcialmente recuperado')">📁 deleted_messages.zip <span class="badge">corrompido</span></button><button onclick="chapter(8)">🎙️ voice_17.wav <span class="badge">0:17</span></button></div></div>`)}
function file17(){render(`<div class="page">${top("IMG_0017")}<div class="card mono">17 — 03 — 21 — 17</div><p class="muted">A sequência não é uma senha comum. Tente relacioná-la aos horários, às mensagens e ao grupo.</p><div class="choices"><button onclick="clue(5);toast('Senha aceita. Nota escondida desbloqueada.')">17 03 21 17</button><button onclick="toast('Senha incorreta')">03 17 17 21</button></div></div>`)}
function notes(){render(`<div class="page">${top("Notas")}<div class="card"><b>LÍVIA — rascunho</b><p>"Se alguma coisa acontecer, não procure uma pessoa. Procure o padrão."</p><p class="mono">17 aparece quando alguém está observando.</p></div><div class="card"><b>GIOVANNA — investigação</b><p class="muted">Noah, Helena, Caio, Miguel, Sofia, Daniel. Todos esconderam alguma coisa.</p></div></div>`)}
function browser(){render(`<div class="page">${top("Navegador")}<div class="card"><b>Pesquisa</b><p class="mono">observatorio_moraes / 17</p></div><div class="card"><b>RESULTADO ARQUIVADO</b><p class="muted">Antigo observatório municipal — fechado após um incêndio em 2017. Registros públicos incompletos.</p></div></div>`)}
function group(){S.group=true;render(`<div class="page">${top("CASO LÍVIA")}<div class="chat"><div class="bubble"><div class="name">HELENA</div>Eu acho que deveríamos parar.</div><div class="bubble"><div class="name">CAIO</div>Parar agora?</div><div class="bubble"><div class="name">MIGUEL</div>Vocês não estão entendendo.</div><div class="bubble"><div class="name">NOAH</div>Ela está aqui.</div><div class="bubble"><div class="name">HELENA</div>Quem?</div><div class="bubble"><div class="name">NOAH</div>…</div><div class="bubble"><div class="name">17</div>Vocês demoraram.</div></div><button class="primary" onclick="clue(9);chapter(9)">INVESTIGAR A MENSAGEM</button></div>`)}
function settings(){render(`<div class="page">${top("Configurações")}<div class="card"><b>Áudio</b><p><button class="secondary" onclick="S.sound=!S.sound;save();toast(S.sound?'Som ligado':'Som desligado')">🔊 ${S.sound?'LIGADO':'DESLIGADO'}</button></p></div><div class="card"><b>Vibração visual</b><p class="muted">Ativa por padrão para eventos de tensão.</p></div><button class="danger secondary" onclick="localStorage.removeItem('arquivo17-save');location.reload()">REINICIAR INVESTIGAÇÃO</button></div>`)}
function ending(){clue(10);let final=S.choices.trust===1?"A VERDADE":S.choices.helena===1?"O SILÊNCIO":"ARQUIVO 17";S.ending=final;save();render(`<div class="credits"><div class="case-title">INVESTIGAÇÃO CONCLUÍDA</div><h2>FINAL: ${final}</h2><p>${final==="A VERDADE"?"Lívia descobriu que o Arquivo 17 era um protocolo clandestino que monitorava qualquer pessoa que reunisse as seis peças do caso. Noah tentou interrompê-lo, mas usou Giovanna como último caminho para expor o sistema.":final==="O SILÊNCIO"?"As pistas apontam para a verdade, mas algumas pessoas preferiram esconder seus papéis. O arquivo permanece incompleto — e alguém apagou a última prova.":"O padrão era a própria investigação. Cada busca registrava um novo nome. Quando Giovanna chegou ao fim, o sistema já sabia quem ela era."}<div class="end">Pistas: ${S.clues.length}/10<br><br><b>FIM DA INVESTIGAÇÃO</b></div><button class="primary" style="margin-top:35px" onclick="afterCredits()">CONTINUAR</button></div>`)}
function afterCredits(){render(`<div class="credits"><h2 style="font-size:22px">…</h2><p style="margin-top:60px">VOCÊ AINDA ESTÁ AÍ?</p><div class="card" style="margin-top:40px;text-align:left"><b>NÚMERO DESCONHECIDO</b><p>Obrigada por encontrar o arquivo.</p><p>Agora eles sabem que você existe.</p></div><p class="red">FIM.</p></div>`)}
function back(){home()}
if(S.first)home();else start();
